spring:
  application:
    name: be-blimp

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3306/blimp
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50

  jpa:
    open-in-view: true

server:
  port: 8081
  servlet:
    context-path: /api/v1

app:
  jwt:
    secret: IrvanPutraNaufalBryanBlimpAnglehackIrvanPutraNaufalBryanBlimpAnglehackIrvanPutraNaufalBryanBlimpAnglehackIrvanPutraNaufalBryanBlimpAnglehack
    expirationMs: 86400000
